### PR TITLE
Add `removeSessionFromErr` function.

### PR DESCRIPTION
**Pull request by mschristiansen**
Add `removeSessionFromErr` function symmetric to `addSessionToErr`.

### CODE REVIEW

**Comment by mschristiansen** [comment]
Build failure on GHC 7.10 and 7.8, but unrelated to this PR as far as I can tell.

**Comment by zohl** [comment]
Thank you, @mschristiansen! Merged.

(The PR is ok, it's just the build is broken at the moment (my fault, I have to fix some dependencies).)

**Comment by mschristiansen** [comment]
Great. Another Hackage release coming soon?

**Comment by zohl** [comment]
Yes, I'll do it on the weekends.

**Comment by zohl** [comment]
Done, there are two releases -- `v0.4.4` and `v0.5.0`.

You can switch to `v0.4.4` without any problems, I backported your PRs there.

As for `v0.5.0`, there are few breaking changes, and even though I did my best to reflect them in the example, I should spend some time on writing proper documentation. (This is related to issue https://github.com/zohl/servant-auth-cookie/issues/26)

**Comment by mschristiansen** [comment]
Great. Thanks!

**Pull request merged**
