### PR TITLE
Refactor and fix the build

### PR DESCRIPTION
**Pull request by mrkkrp**
This is work is progress. There are a lot of things to change and it's just how it currently looks. I made some comments:

* [here](https://github.com/zohl/servant-auth-cookie/commit/488fd7c91476a1d147a282871395b1c09376fa75)
* […and here](https://github.com/zohl/servant-auth-cookie/commit/aba61c8ef7f3b54f987bc2df5282e071204402c0)

However there are things that may have forgotten to comment on. Feel free to ask something.

Please don't merge yet. When I'm done I'll tell you explicitly and rebase so we have a neat commit log.

When it's finished I'll probably return the internal module, we'll see. Tests will be adjusted too, the build fixed, and it should be mostly done. I'll try to finish as soon as possible.

I changed some stylistic bits to make it look more conventional and idiomatic too, I'm not sure how you feel about it.

Please feel free to comment and ask. Thanks.

### CODE REVIEW

**Comment by mrkkrp** [comment]
Will finish tomorrow.

**Comment by zohl** [comment]
Wow, this is amazing! Thank you very much for your contributions.
There is a lot of things I wasn't aware of, so this is valuable learning experience for me. Feel free to change everything you need to adjust.

Cc me, once you finish, I'll be glad to merge the PR.

**Comment by mrkkrp** [comment]
Perhaps we should use `Expires` instead of `Max-Age`: http://mrcoles.com/blog/cookies-max-age-vs-expires/.

**Comment by mrkkrp** [comment]
OK, I have finished with the library, refreshed the example, and almost re-organized the tests. Note that I switched from vanilla HUnit to Hspec, which is much nicer, you probably can see it for yourself. I also plan to use QuickCheck a lot in the tests. We already have some property-tests for sessions but they fail.

I'm not sure why the tests fail. The exception thrown is `IncorrectMAC`, but I don't know yet why it is incorrect. Could you take a look at this? I'll return to this tomorrow and finish the tests. I'll also try to investigate why some tests fail.

If you cannot help with identifying why we get `IncorrectMAC` exception, could you give me a link to description of the algorithm you implement here?

**Comment by mrkkrp** [comment]
@zohl, I think it's done. You can merge, but please don't release new major version yet, I want to try it in our application to see how it works in a more-or-less real project.

**Comment by zohl** [comment]
Great!
Sorry, I wasn't fast to respond, but yes, the issue was in resetting the key on every call of `acsServerKey`.

Before I merge it, there is one small question: is `runPut` in `encryptCookie` necessary? The code in `decryptCookie` doesn't rely on `Data.Serialize`, so simple string concatenation should do the trick.

**Comment by mrkkrp** [comment]
In this case there is no real difference. I can amend if you want. In other cases `runPut` will be faster than manual construction (especially if it's not done in as one `concat` call) because it's essential writer monad with byte string bulider as its monoid.

**Comment by zohl** [comment]
Alright, this makes a sense. Merged. Thank you again!

**Pull request merged**
